services:
  
  vault-server:
    container_name: vault-webapp-integration-poc-vault-server
    build:
        context: ./vault-server
        dockerfile: Dockerfile
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
    cap_add:
      - IPC_LOCK
    command: server
    restart: always
    
  vault-init:
    container_name: vault-webapp-integration-poc-vault-init
    build:
        context: ./vault-init
        dockerfile: Dockerfile
    environment:
      VAULT_ADDR: http://vault-server:8200
      MYSQL_INITIAL_ROOT_PASSWORD: ${MYSQL_INITIAL_ROOT_PASSWORD}
    volumes:
      - vault-agent-data:/vault/file/agent/
    depends_on:
      - vault-server
      - database
    restart: on-failure
  
  database:
    container_name: vault-webapp-integration-poc-database
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_INITIAL_ROOT_PASSWORD}
      MYSQL_DATABASE: notes_webapp
    depends_on:
      - vault-server
    restart: always

  webapp:
    container_name: vault-webapp-integration-poc-webapp
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "1337:5000"
    volumes:
      - vault-agent-data:/vault-agent/ids/
    depends_on:
      - vault-server
      - database
      - vault-init
    restart: always

volumes:
  vault-agent-data:

